spring.application.name=mod

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/losdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Resh@23.10.2006

# JPA/Hibernate settings , communication between sb & db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

